platform :ios, '10.0'

target 'TexturedPopoverBackgroundDemo' do
  use_frameworks!
  
  pod 'TexturedPopoverBackgroundView',  :path => '..'
  
  target 'TexturedPopoverBackgroundDemoTests' do
    :inherit_all
  end
  
end


